#!/usr/bin/env bash

BASE_DIR=$(dirname $0)

echo "Installing dot configuration files"
cp -frv ${BASE_DIR}/.vimrc /home/kali/.vimrc
cp -frv ${BASE_DIR}/.zshrc /home/kali/.zshrc
chown kali: /home/kali/.vimrc
chown kali: /home/kali/.zshrc
chmod 644 /home/kali/.vimrc
chmod 644 /home/kali/.zshrc
